# Use this open statement to create an OpenGL view:
/vis/open OGL

# Draw geometry:
/vis/drawVolume

# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 45 45

# Zoom up/down:
/vis/viewer/zoom 1.5

# Draw coordinate axes:
/vis/scene/add/axes 0 0 0 10 cm

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
